const SELECT_USER = 'SELECT_USER',
			CHANGE_COUNTER = 'CHANGE_COUNTER',
			CHANGE_LIST = 'CHANGE_LIST',
			GET_CONTACTS = 'GET_CONTACTS',
			DISPLAY_CONTACTS = 'DISPLAY_CONTACTS',
			GET_ITEM_PHOTO = 'GET_ITEM_PHOTO',
			DISPLAY_ITEMS_PHOTO = 'DISPLAY_ITEMS_PHOTO',
			GET_ITEM_PHOTO2 = 'GET_ITEM_PHOTO2';


export {
	SELECT_USER,
	CHANGE_COUNTER,
	CHANGE_LIST,
	GET_CONTACTS,
	DISPLAY_CONTACTS,
	GET_ITEM_PHOTO,
	DISPLAY_ITEMS_PHOTO,
	GET_ITEM_PHOTO2,
}