const SELECT_USER = 'SELECT_USER',
			CHANGE_COUNTER = 'CHANGE_COUNTER',
			CHANGE_LIST = 'CHANGE_LIST',
			GET_CONTACTS = 'GET_CONTACTS',
			DISPLAY_CONTACTS = 'DISPLAY_CONTACTS';


export {
	SELECT_USER,
	CHANGE_COUNTER,
	CHANGE_LIST,
	GET_CONTACTS,
	DISPLAY_CONTACTS,
}